[package]
name = "todolist"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde = { version = "^1.0.229", features = ["serde_derive"] }
http = "^1.5.0"
axum = "0.8.9"
utoipa = { version = "5.5.0", features = ["chrono"] }
utoipa-axum = "^0.2.0"
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
tower-http = { version = "0.7.0", features = ["add-extension", "trace", "cors", "request-id"] }
tracing = { version = "0.1.44" }
tracing-subscriber = { version = ">=0.3.20", features = ["env-filter", "chrono"] }
clap = { version = "4.6.6", features = ["derive", "env"] }
# runtime
tokio = { version = "^1.53.1", features = ["rt-multi-thread", "macros"] }
tokio-postgres = { version = "0.7.18", features = ["with-serde_json-1", "with-chrono-0_4"] }
thiserror = "2"
# project
cqrs-rust-lib = { path = "../..", features = ["rest", "postgres"] }

[package.metadata.cargo-machete]
ignored = ["thiserror"]
